[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "som2cg"
version = "0.13.0.dev4"
description = "Coarse-graining soil organic matter models to Martini 3"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Lorenz Dettmann" }]
dependencies = [
  "mdanalysis",
  "rdkit",
  "pyyaml",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
som2cg = "som2cg.som2cg:main"
